import React from 'react'
import styled from 'styled-components'
import Head from 'next/head'
import SlimeBG from '../../components/Slime-BG';
import Navbar from '../../components/Navbar';
import Image from 'next/image'

const StyledMain = styled.main`
  & {
	display: grid;
	margin-left: 15vw;
	margin-top: 10vh;
	font-size: 40px;
  }

  & h1 {
	font-size: 70px;
	font-weight: 100;
	text-transform: uppercase;
  }

  & a {
	color: #fff;
	text-decoration: none;
  }

  & ul {
	list-style: none;
	margin: 0;
  }

  & li {
	display: inline-block;
	margin-right: 3rem;
  }
`

const Container = styled.li`
	& {
		position: relative;
		width: 25rem;
		height: 25rem;	
	}

	& a div:first-child {		// image header
		display: grid;
		place-content: center;
		margin-top: -3.4rem;
		text-shadow: 0 0 2rem black;
		transition: all ease-in-out 500ms
	}

	&:hover a div:first-child {
		text-shadow: 0 0 0 black;
	}

	& a div:last-child { 		// div generated by next/Image (contains <img>)
		border-radius: 1rem;
		overflow: hidden;	
		box-shadow: 0 0 2rem black;
		transition: all ease-in-out 500ms
	}

	&:hover a div:last-child {
		box-shadow: 0 0 0 black;
	}
`

export default function index() {
	return (
		<>
			<Head>
				<title> Projects </title>
			</Head>

			<Navbar />
			<SlimeBG />
			<StyledMain>
				<h1> Projects </h1>
				<ul>
					<Container>
						<a href="/projects/haiirOS"> 
							<div>HaiirOS</div>
							<Image quality="100" layout="fill" src="/static/project-thumbnails/haiirOS.png" alt="" />
						</a>
					</Container>
					<Container>
						<a href="/projects/greychain">
							<div>Greychain</div>
							<Image quality="100" layout="fill" src="/static/project-thumbnails/greychain.png" alt="" />
						</a>
					</Container>
				</ul>
			</StyledMain>
		</>
	);
}
