import React from 'react'
import styled from 'styled-components'
import Head from 'next/head'
import SlimeBG from '../../components/Slime-BG';
import Navbar from '../../components/Navbar';
import Image from 'next/image'

const StyledMain = styled.main`
  & {
	display: grid;
	margin-top: 0;
	font-size: 1.5rem;
  }

  & h1 {
	margin-left: 15vw;
	margin-top: 17vh;
	margin-bottom: 0;
	font-size: 2.3rem;
	font-weight: 100;
	text-transform: uppercase;
  }

  & a {
	color: #fff;
	text-decoration: none;
  }

  & ul {
	list-style: none;
	margin: 3.5rem;
	margin-left: 12vw;
  }

  & li {
	display: inline-block;
	margin-right: 3rem;
  }
`

const Container = styled.li`
	& {
		position: relative;
		width: 20rem;
		height: 20rem;	
	}

	& a div:first-child {		// image header
		display: grid;
		place-content: center;
		margin-top: -2.4rem;
		text-shadow: 0 0 2rem rgba( 0, 0, 0, 0.5 );
		transition: all ease-in-out 350ms
	}

	&:hover a div:first-child {
		text-shadow: 0 0 0 rgba( 0, 0, 0, 0.5 );
	}

	& a div:last-child { 		// div generated by next/Image (contains <img>)
		border-radius: 1.25rem;
		overflow: hidden;	
		box-shadow: 0 0 2rem rgba( 0, 0, 0, 0.5 );
		transition: all ease-in-out 350ms
	}

	&:hover a div:last-child {
		box-shadow: 0 0 0 rgba( 0, 0, 0, 0.5 );
	}
`

export default function index() {
	return (
		<>
			<Head>
				<title> Projects </title>
			</Head>

			<Navbar />
			<SlimeBG />
			<StyledMain>
				<h1> Projects </h1>
				<ul>
					<Container>
						<a href="/projects/haiirOS"> 
							<div>HaiirOS</div>
							<Image quality="100" layout="fill" src="/static/project-thumbnails/haiirOS.png" alt="" />
						</a>
					</Container>
					<Container>
						<a href="/projects/greychain">
							<div>Greychain</div>
							<Image quality="100" layout="fill" src="/static/project-thumbnails/greychain.png" alt="" />
						</a>
					</Container>
					<Container>
						<a href="/projects/tempest-engine">
							<div>Tempest-Engine</div>
							<Image quality="100" layout="fill" src="/static/project-thumbnails/tempest-engine.png" alt="" />
						</a>
					</Container>
				</ul>
			</StyledMain>
		</>
	);
}
